// Script generated by Codex
// To use just run command $ npm run clear-db

const path = require("path");
const Database = require("better-sqlite3");

const dbPath = path.join(__dirname, "data", "pass.db");
const db = new Database(dbPath);

try {
    const result = db.prepare("DELETE FROM users").run();

    db.prepare(`
        DELETE FROM sqlite_sequence
        WHERE name = ? 
    `).run("users");

    db.exec("VACUUM");

    console.log(`Deleted ${result.changes} user(s).`);
} finally {
    db.close();
}